services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main-app
      - checkout-app
    networks:
      - ecommerce-network

  main-app:
    build:
      context: ../main-app
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000" 
    networks:
      - ecommerce-network

  checkout-app:
    build:
      context: ../checkout-app
      dockerfile: Dockerfile
    environment:
      - PORT=3001 
    ports:
      - "3001:3001" 
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge